[package]
name = "blackferrari2/fun"
version = "0.3.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Effects!"

exclude = [
    "aftman.toml", 
    "README.md",
    "test.project.json"
]

[dependencies]
Signal = "sleitnick/signal@2.0.1"
FixedUpdate = "blackferrari2/fixedupdate@0.1.2"