[package]
name = "blackferrari2/fixedupdate"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "provides functionality similar to unitys FixedUpdate (i think. i never used unity xD). Adapted from Smile4."

exclude = [
    "aftman.toml", 
    "README.md",
    "test.project.json"
]

[dependencies]
Signal = "sleitnick/signal@2.0.1"